// <auto-generated />
using System;
using ConverTank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConverTank.Migrations
{
    [DbContext(typeof(ConteudoBanco))]
    [Migration("20260601174535_Teste2")]
    partial class Teste2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConverTank.Models.Combustivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Combustiveis");
                });

            modelBuilder.Entity("ConverTank.Models.Entidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Entidades", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ConverTank.Models.Medicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataMedicao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TanqueId")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TanqueId");

                    b.ToTable("Medicoes");
                });

            modelBuilder.Entity("ConverTank.Models.Tanque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombustivelId")
                        .HasColumnType("int");

                    b.Property<double>("Comprimento")
                        .HasColumnType("float");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<int>("PostoId")
                        .HasColumnType("int");

                    b.Property<double>("Raio")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CombustivelId");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("PostoId");

                    b.ToTable("Tanques");
                });

            modelBuilder.Entity("ConverTank.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Administrador")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConverTank.Models.UsuarioPosto", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PostoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioPostoPostoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioPostoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PostoId");

                    b.HasIndex("PostoId");

                    b.HasIndex("UsuarioPostoUsuarioId", "UsuarioPostoPostoId");

                    b.ToTable("UsuariosPostos");
                });

            modelBuilder.Entity("ConverTank.Models.Fabricante", b =>
                {
                    b.HasBaseType("ConverTank.Models.Entidade");

                    b.ToTable("Fabricantes", (string)null);
                });

            modelBuilder.Entity("ConverTank.Models.Fornecedor", b =>
                {
                    b.HasBaseType("ConverTank.Models.Entidade");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("ConverTank.Models.Posto", b =>
                {
                    b.HasBaseType("ConverTank.Models.Entidade");

                    b.ToTable("Postos", (string)null);
                });

            modelBuilder.Entity("ConverTank.Models.Combustivel", b =>
                {
                    b.HasOne("ConverTank.Models.Fornecedor", "Fornecedor")
                        .WithMany("Combustiveis")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ConverTank.Models.Medicao", b =>
                {
                    b.HasOne("ConverTank.Models.Tanque", "Tanque")
                        .WithMany("Medicoes")
                        .HasForeignKey("TanqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("ConverTank.Models.Tanque", b =>
                {
                    b.HasOne("ConverTank.Models.Combustivel", "Combustivel")
                        .WithMany()
                        .HasForeignKey("CombustivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConverTank.Models.Fabricante", "Fabricante")
                        .WithMany("Tanques")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ConverTank.Models.Posto", "Posto")
                        .WithMany("Tanques")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Combustivel");

                    b.Navigation("Fabricante");

                    b.Navigation("Posto");
                });

            modelBuilder.Entity("ConverTank.Models.UsuarioPosto", b =>
                {
                    b.HasOne("ConverTank.Models.Posto", "Posto")
                        .WithMany("UsuarioPostos")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConverTank.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPostos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConverTank.Models.UsuarioPosto", null)
                        .WithMany("UsuarioPostos")
                        .HasForeignKey("UsuarioPostoUsuarioId", "UsuarioPostoPostoId");

                    b.Navigation("Posto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConverTank.Models.Fabricante", b =>
                {
                    b.HasOne("ConverTank.Models.Entidade", null)
                        .WithOne()
                        .HasForeignKey("ConverTank.Models.Fabricante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConverTank.Models.Fornecedor", b =>
                {
                    b.HasOne("ConverTank.Models.Entidade", null)
                        .WithOne()
                        .HasForeignKey("ConverTank.Models.Fornecedor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConverTank.Models.Posto", b =>
                {
                    b.HasOne("ConverTank.Models.Entidade", null)
                        .WithOne()
                        .HasForeignKey("ConverTank.Models.Posto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConverTank.Models.Tanque", b =>
                {
                    b.Navigation("Medicoes");
                });

            modelBuilder.Entity("ConverTank.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPostos");
                });

            modelBuilder.Entity("ConverTank.Models.UsuarioPosto", b =>
                {
                    b.Navigation("UsuarioPostos");
                });

            modelBuilder.Entity("ConverTank.Models.Fabricante", b =>
                {
                    b.Navigation("Tanques");
                });

            modelBuilder.Entity("ConverTank.Models.Fornecedor", b =>
                {
                    b.Navigation("Combustiveis");
                });

            modelBuilder.Entity("ConverTank.Models.Posto", b =>
                {
                    b.Navigation("Tanques");

                    b.Navigation("UsuarioPostos");
                });
#pragma warning restore 612, 618
        }
    }
}
